{"uuid": "51184ea8-94e6-46e1-8c80-ec79bfe6fcaf", "children": ["814cfc9d-f37f-4121-b0a0-9b434e7c8e19"], "befores": [{"name": "log_on_faliure", "status": "passed", "start": 1659272068898, "stop": 1659272068898}], "afters": [{"name": "log_on_faliure::0", "status": "broken", "statusDetails": {"message": "AttributeError: 'Function' object has no attribute 'rep_call'\n", "trace": "  File \"C:\\Users\\dines\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\allure_commons\\_allure.py\", line 200, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"C:\\Users\\dines\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\_pytest\\fixtures.py\", line 899, in _teardown_yield_fixture\n    next(it)\n  File \"C:\\Users\\dines\\AppiumPageObjectModel\\TestCases\\conftest.py\", line 35, in log_on_faliure\n    if item.rep_call.failed:\n"}, "start": 1659272093607, "stop": 1659272094262}], "start": 1659272068898, "stop": 1659272094262}